### ISSUE TITLE
Taglib caused kdeinit5 to crash while i was moving music files from phone to laptop via USB

### ISSUE THREAD

**Issue by mystiquewolf** [taglib/taglib#1024]
Application: kdeinit5 (kdeinit5), signal: Segmentation fault
```
[KCrash Handler]
#4  TagLib::MP4::Tag::itemMap (this=0x0) at ./taglib/mp4/mp4tag.cpp:799
#5  0x00007f1012539494 in parseMP4Tag<TagLib::MP4::File> (img=..., file=...) at ./thumbnail/audiocreator.cpp:119
#6  AudioCreator::create (this=<optimized out>, path=..., img=...) at ./thumbnail/audiocreator.cpp:176
#7  0x00007f1024a3461a in ThumbnailProtocol::get (this=0x7fff37ca34c0, url=...) at ./thumbnail/thumbnail.cpp:255
#8  0x00007f101fed1fae in KIO::SlaveBase::dispatch (this=0x7fff37ca34c0, command=67, data=...) at ./src/core/slavebase.cpp:1216
#9  0x00007f101fed2906 in KIO::SlaveBase::dispatchLoop (this=0x7fff37ca34c0) at ./src/core/slavebase.cpp:335
#10 0x00007f1024a32961 in kdemain (argc=<optimized out>, argv=0x5599b7beb210) at ./thumbnail/thumbnail.cpp:138
#11 0x00005599b7653936 in launch (argc=argc@entry=4, _name=_name@entry=0x5599b7bead68 "/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/thumbnail.so", args=<optimized out>, args@entry=0x5599b7beada3 "thumbnail", cwd=cwd@entry=0x0, envc=envc@entry=0, envs=envs@entry=0x5599b7beae1c "", reset_env=false, tty=0x0, avoid_loops=false, startup_id_str=0x5599b765623d "0") at ./src/kdeinit/kinit.cpp:692
#12 0x00005599b76551f1 in handle_launcher_request (sock=4, who=who@entry=0x5599b76561f2 "launcher") at ./src/kdeinit/kinit.cpp:1130
#13 0x00005599b76559f7 in handle_requests (waitForPid=waitForPid@entry=0) at ./src/kdeinit/kinit.cpp:1323
#14 0x00005599b76501ba in main (argc=3, argv=<optimized out>) at ./src/kdeinit/kinit.cpp:1761
```
Please see here: https://bugs.kde.org/show_bug.cgi?id=439034

**Comment by scotchi** [comment]
This really doesn't look like a TagLib bug.  Looks like there needs to be a check for null in the KDE code.  I've added a comment there.
