### ISSUE TITLE
 Heap-buffer-overflow in frame parsing

### ISSUE THREAD

**Issue by LukasReschke** [taglib/taglib#1173]
There seems to be heap-buffer-overflow with regards to the frame parsing. 

# Reproduction steps
You can reproduce this with the `tagreader_c` example shipped within the examples folder. As input use the attached file called [minimized_result.mp3](https://github.com/taglib/taglib/files/13310211/minimized_result.mp3.zip).

```
 ./tagreader_c minimized_result.mp3
```

# Address Sanitizer Output
```
=================================================================
==2384415==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000c00 at pc 0xaaaaaaccbd4c bp 0xffffffffd760 sp 0xffffffffd750
READ of size 8 at 0x602000000c00 thread T0
    #0 0xaaaaaaccbd48 in std::__uniq_ptr_impl<TagLib::ByteVector::ByteVectorPrivate, std::default_delete<TagLib::ByteVector::ByteVectorPrivate> >::_M_ptr() const /usr/include/c++/13/bits/unique_ptr.h:199
    #1 0xaaaaaaccbd48 in std::unique_ptr<TagLib::ByteVector::ByteVectorPrivate, std::default_delete<TagLib::ByteVector::ByteVectorPrivate> >::get() const /usr/include/c++/13/bits/unique_ptr.h:470
    #2 0xaaaaaaccbd48 in std::unique_ptr<TagLib::ByteVector::ByteVectorPrivate, std::default_delete<TagLib::ByteVector::ByteVectorPrivate> >::operator*() const /usr/include/c++/13/bits/unique_ptr.h:454
    #3 0xaaaaaaccbd48 in TagLib::ByteVector::ByteVector(TagLib::ByteVector const&) /home/lukas/fuzzing_taglib/taglib_orig/taglib/toolkit/tbytevector.cpp:345
    #4 0xaaaaaabb31e0 in TagLib::ID3v2::AttachedPictureFrame::picture() const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/frames/attachedpictureframe.cpp:111
    #5 0xaaaaaab80b38 in TagLib::ID3v2::Tag::complexProperties(TagLib::String const&) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:479
    #6 0xaaaaaae6aed4 in TagLib::TagUnion::complexProperties(TagLib::String const&) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/tagunion.cpp:144
    #7 0xaaaaaad1b904 in TagLib::File::complexProperties(TagLib::String const&) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/toolkit/tfile.cpp:116
    #8 0xaaaaaae7a8b4 in TagLib::FileRef::complexProperties(TagLib::String const&) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:357
    #9 0xaaaaaaae5adc in taglib_complex_property_get /home/lukas/fuzzing_taglib/taglib_orig/bindings/c/tag_c.cpp:577
    #10 0xaaaaaaad30e4 in main /home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c.c:100
    #11 0xfffff7397580 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #12 0xfffff7397654 in __libc_start_main_impl ../csu/libc-start.c:360
    #13 0xaaaaaaad6cac in _start (/home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c+0x36cac) (BuildId: ef867d14618a02e5354aeff0fe808774b79383e5)

0x602000000c00 is located 0 bytes after 16-byte region [0x602000000bf0,0x602000000c00)
freed by thread T0 here:
    #0 0xfffff7989adc in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:164
    #1 0xaaaaaab3ae68 in TagLib::ID3v2::FrameFactory::prepareFrameHeader(TagLib::ByteVector&, TagLib::ID3v2::Header const*) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2framefactory.cpp:129
    #2 0xaaaaaab3dfc8 in TagLib::ID3v2::FrameFactory::createFrame(TagLib::ByteVector const&, TagLib::ID3v2::Header const*) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2framefactory.cpp:183
    #3 0xaaaaaab6bbc0 in TagLib::ID3v2::Tag::parse(TagLib::ByteVector const&) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:856
    #4 0xaaaaaab867d4 in TagLib::ID3v2::Tag::read() /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:783
    #5 0xaaaaaab87b78 in TagLib::ID3v2::Tag::Tag(TagLib::File*, long, TagLib::ID3v2::FrameFactory const*) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:116
    #6 0xaaaaaab113ec in TagLib::MPEG::File::read(bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/mpegfile.cpp:460
    #7 0xaaaaaab137c8 in TagLib::MPEG::File::File(TagLib::IOStream*, TagLib::ID3v2::FrameFactory*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/mpegfile.cpp:148
    #8 0xaaaaaae6d2f4 in detectByExtension /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:138
    #9 0xaaaaaae81354 in TagLib::FileRef::parse(char const*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:484
    #10 0xaaaaaae83a9c in TagLib::FileRef::FileRef(char const*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:293
    #11 0xaaaaaaad9468 in taglib_file_new /home/lukas/fuzzing_taglib/taglib_orig/bindings/c/tag_c.cpp:117
    #12 0xaaaaaaad2c94 in main /home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c.c:50
    #13 0xfffff7397580 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0xfffff7397654 in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0xaaaaaaad6cac in _start (/home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c+0x36cac) (BuildId: ef867d14618a02e5354aeff0fe808774b79383e5)

previously allocated by thread T0 here:
    #0 0xfffff7988a1c in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0xaaaaaab3ab38 in TagLib::ID3v2::FrameFactory::prepareFrameHeader(TagLib::ByteVector&, TagLib::ID3v2::Header const*) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2framefactory.cpp:119
    #2 0xaaaaaab3dfc8 in TagLib::ID3v2::FrameFactory::createFrame(TagLib::ByteVector const&, TagLib::ID3v2::Header const*) const /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2framefactory.cpp:183
    #3 0xaaaaaab6bbc0 in TagLib::ID3v2::Tag::parse(TagLib::ByteVector const&) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:856
    #4 0xaaaaaab867d4 in TagLib::ID3v2::Tag::read() /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:783
    #5 0xaaaaaab87b78 in TagLib::ID3v2::Tag::Tag(TagLib::File*, long, TagLib::ID3v2::FrameFactory const*) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/id3v2/id3v2tag.cpp:116
    #6 0xaaaaaab113ec in TagLib::MPEG::File::read(bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/mpegfile.cpp:460
    #7 0xaaaaaab137c8 in TagLib::MPEG::File::File(TagLib::IOStream*, TagLib::ID3v2::FrameFactory*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/mpeg/mpegfile.cpp:148
    #8 0xaaaaaae6d2f4 in detectByExtension /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:138
    #9 0xaaaaaae81354 in TagLib::FileRef::parse(char const*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:484
    #10 0xaaaaaae83a9c in TagLib::FileRef::FileRef(char const*, bool, TagLib::AudioProperties::ReadStyle) /home/lukas/fuzzing_taglib/taglib_orig/taglib/fileref.cpp:293
    #11 0xaaaaaaad9468 in taglib_file_new /home/lukas/fuzzing_taglib/taglib_orig/bindings/c/tag_c.cpp:117
    #12 0xaaaaaaad2c94 in main /home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c.c:50
    #13 0xfffff7397580 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0xfffff7397654 in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0xaaaaaaad6cac in _start (/home/lukas/fuzzing_taglib/taglib_orig/examples/tagreader_c+0x36cac) (BuildId: ef867d14618a02e5354aeff0fe808774b79383e5)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/13/bits/unique_ptr.h:199 in std::__uniq_ptr_impl<TagLib::ByteVector::ByteVectorPrivate, std::default_delete<TagLib::ByteVector::ByteVectorPrivate> >::_M_ptr() const
Shadow bytes around the buggy address:
  0x602000000980: fa fa fd fa fa fa 00 fa fa fa 00 fa fa fa 00 00
  0x602000000a00: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 00 fa
  0x602000000a80: fa fa 00 fa fa fa 00 00 fa fa fd fa fa fa fd fa
  0x602000000b00: fa fa fd fa fa fa 00 fa fa fa 00 fa fa fa 00 00
  0x602000000b80: fa fa fd fa fa fa 00 fa fa fa 00 fa fa fa fd fd
=>0x602000000c00:[fa]fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x602000000c80: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x602000000d00: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fd
  0x602000000d80: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x602000000e00: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x602000000e80: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2384415==ABORTING
```

**Comment by ufleisch** [comment]
Thank you very much for the report. I naively assumed that frames with "APIC" ID are `AttachedPictureFrame` and accessed them. Now this is checked using a `dynamic_cast`.
