### ISSUE TITLE
symbol not found in flat namespace

### ISSUE THREAD

**Issue by gingerbeardman** [taglib/taglib#1206]
problem with taglib when installing/running PyMusicLooper https://github.com/arkrow/PyMusicLooper/issues/28

- macOS 14.2.1 Sonoma
- Architecture: ARM64 (Apple silicon)
- CPU: M1 Pro

```
% pymusiclooper                      
Traceback (most recent call last):
  File "/Users/matt/.local/bin/pymusiclooper", line 7, in <module>
    from pymusiclooper.__main__ import cli
  File "/Users/matt/Library/Application Support/pipx/venvs/pymusiclooper/lib/python3.11/site-packages/pymusiclooper/__main__.py", line 3, in <module>
    from .cli import cli_main
  File "/Users/matt/Library/Application Support/pipx/venvs/pymusiclooper/lib/python3.11/site-packages/pymusiclooper/cli.py", line 20, in <module>
    from .core import MusicLooper
  File "/Users/matt/Library/Application Support/pipx/venvs/pymusiclooper/lib/python3.11/site-packages/pymusiclooper/core.py", line 18, in <module>
    taglib = lazy.load("taglib")
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/matt/Library/Application Support/pipx/venvs/pymusiclooper/lib/python3.11/site-packages/lazy_loader/__init__.py", line 205, in load
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/matt/Library/Application Support/pipx/venvs/pymusiclooper/lib/python3.11/site-packages/taglib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6TagLib10StringList6appendERKNS_6StringE'
```

**Comment by ufleisch** [comment]
I doubt that this is a bug in TagLib. Perhaps the package is simply built incorrectly.

**Comment by gingerbeardman** [comment]
I think it's somehow a problem with parts of the build (taglib) being compiled for the wrong architecture

Apologies if this is the wrong place for this report, I am a python user only my development skills lay elsewhere.
