### ISSUE TITLE
Infinite loop with fuzzed file

### ISSUE THREAD

**Issue by tholin** [taglib/taglib#482]
Parsing the following file with the tagreader example results in an infinite loop.
https://www.dropbox.com/s/ly8u5ge3qp0atj8/taglib_wavpack_infloop.wv

```
$ gdb --args ~/repository/taglib/build/examples/tagreader taglib_wavpack_infloop.wv
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/taglib/build/examples/tagreader...done.
(gdb) r
Starting program: /home/cocobo/repository/taglib/build/examples/tagreader taglib_wavpack_infloop.wv
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
******************** "taglib_wavpack_infloop.wv" ********************
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7a5bb50 in __gnu_cxx::__normal_iterator<char const*, std::vector<char, std::allocator<char> > >::operator- (this=0x7fffffffd490, __n=@0x7fffffffcb48: 4)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/bits/stl_iterator.h:787
787           { return __normal_iterator(_M_current - __n); }
(gdb) bt full
#0  0x00007ffff7a5bb50 in __gnu_cxx::__normal_iterator<char const*, std::vector<char, std::allocator<char> > >::operator- (this=0x7fffffffd490, __n=@0x7fffffffcb48: 4)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/bits/stl_iterator.h:787
No locals.
#1  0x00007ffff7a5c75e in std::reverse_iterator<__gnu_cxx::__normal_iterator<char const*, std::vector<char, std::allocator<char> > > >::operator+ (this=0x7fffffffd490, __n=4)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/bits/stl_iterator.h:232
No locals.
#2  0x00007ffff7a57859 in TagLib::findVector<std::reverse_iterator<__gnu_cxx::__normal_iterator<char const*, std::vector<char, std::allocator<char> > > > > (dataBegin=..., dataEnd=..., patternBegin=..., patternEnd=..., 
    offset=0, byteAlign=1) at /home/cocobo/repository/taglib/taglib/toolkit/tbytevector.cpp:166
        itBuffer = {<std::iterator<std::random_access_iterator_tag, char, long, char const*, char const&>> = {<No data fields>}, current = 114 'r'}
        itPattern = {<std::iterator<std::random_access_iterator_tag, char, long, char const*, char const&>> = {<No data fields>}, current = 118 'v'}
        step = 4
        dataSize = 1024
        patternSize = 4
        lastOccurrence = {4 <repeats 107 times>, 3, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 1, 4 <repeats 137 times>}
        it = {<std::iterator<std::random_access_iterator_tag, char, long, char const*, char const&>> = {<No data fields>}, current = 114 'r'}
#3  0x00007ffff7a4d829 in TagLib::ByteVector::rfind (this=0x7fffffffd510, pattern=..., offset=0, byteAlign=1)
    at /home/cocobo/repository/taglib/taglib/toolkit/tbytevector.cpp:584
        pos = 32767
#4  0x00007ffff7a6fd32 in TagLib::File::rfind (this=0x617d00, pattern=..., fromOffset=294, before=...)
    at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:384
        location = 140737348192891
        buffer = {_vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x616b40}, d = 0x617e30}
        originalPosition = 326
        bufferOffset = 326
#5  0x00007ffff7a9da03 in TagLib::WavPack::Properties::seekFinalIndex (this=0x6181d0)
    at /home/cocobo/repository/taglib/taglib/wavpack/wavpackproperties.cpp:183
        data = {_vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x616b40}, d = 0x618bb0}
        flags = 32767
        blockSamples = 0
        version = 8256
        blockIndex = 2209
        blockID = {_vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x616b40}, d = 0x6184a0}
        offset = 294
#6  0x00007ffff7a9d544 in TagLib::WavPack::Properties::read (this=0x6181d0)
    at /home/cocobo/repository/taglib/taglib/wavpack/wavpackproperties.cpp:165
        flags = 1029
        samples = 4294967295
#7  0x00007ffff7a9c413 in TagLib::WavPack::Properties::Properties (this=0x6181d0, file=0x617d00, 
    streamLength=2209, style=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/wavpack/wavpackproperties.cpp:82
        data = {_vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dce5f0 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x616b40}, d = 0x617cd0}
#8  0x00007ffff7a9abf9 in TagLib::WavPack::File::read (this=0x617d00, readProperties=true)
    at /home/cocobo/repository/taglib/taglib/wavpack/wavpackfile.cpp:277
No locals.
#9  0x00007ffff7a983c5 in TagLib::WavPack::File::File (this=0x617d00, 
    file=0x7fffffffde80 "taglib_wavpack_infloop.wv", readProperties=true, 
    propertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/wavpack/wavpackfile.cpp:90
No locals.
#10 0x00007ffff7b7ae1c in TagLib::FileRef::create (fileName=0x7fffffffde80 "taglib_wavpack_infloop.wv", 
    readAudioProperties=true, audioPropertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:257
        it = 
        ext = {_vptr.String = 0x7ffff7dce4f0 <vtable for TagLib::String+16>, static null = {
            _vptr.String = 0x7ffff7dce4f0 <vtable for TagLib::String+16>, 
            static null = <same as static member of an already seen type>, 
            static WCharByteOrder = TagLib::String::UTF16LE, d = 0x616af0}, 
          static WCharByteOrder = TagLib::String::UTF16LE, d = 0x617db0}
#11 0x00007ffff7b77ad1 in TagLib::FileRef::FileRef (this=0x7fffffffd8d0, 
    fileName=0x7fffffffde80 "taglib_wavpack_infloop.wv", readAudioProperties=true, 
    audioPropertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:83
No locals.
#12 0x00000000004048a7 in main (argc=2, argv=0x7fffffffda58)
    at /home/cocobo/repository/taglib/examples/tagreader.cpp:41
        f = {_vptr.FileRef = 0x7ffff7dd0610 <vtable for TagLib::FileRef+16>, d = 0x404792 <main+34>}
        i = 1
#13 0x00007ffff6c76dc5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#14 0x00000000004046a9 in _start ()
No symbol table info available.
(gdb) b tfile.cpp:372
Breakpoint 1 at 0x7ffff7a6fc28: file /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp, line 372.
(gdb) c
Continuing.

Breakpoint 1, TagLib::File::rfind (this=0x617d00, pattern=..., fromOffset=294, before=...)
    at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:372
372         seek(fromOffset + -1 * int(bufferSize()), Beginning);
(gdb) print fromOffset
$1 = 294
(gdb) print bufferSize()
$2 = 1024
(gdb) s
TagLib::File::bufferSize () at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:495
495     {
(gdb) finish 
Run till exit from #0  TagLib::File::bufferSize ()
    at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:495
0x00007ffff7a6fc2d in TagLib::File::rfind (this=0x617d00, pattern=..., fromOffset=294, before=...)
    at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:372
372         seek(fromOffset + -1 * int(bufferSize()), Beginning);
Value returned is $3 = 1024
(gdb) s
TagLib::File::seek (this=0x617d00, offset=140737348159554, 
    p=(TagLib::File::Current | TagLib::File::End | unknown: 32764))
    at /home/cocobo/repository/taglib/taglib/toolkit/tfile.cpp:436
436     {
(gdb) print offset
$4 = 140737348159554
```

**Comment by TsudaKageyu** [comment]
I can fix this bug immediately, but it requires #484 first.
